// Focl's domain state: one pure reducer over everything that gets
// persisted. UI state (current screen, drafts, toasts) stays in App.jsx —
// only data that outlives a session lives here.
//
// Reducers stay pure: ids are generated by callers and passed in actions,
// and side effects (notifications, haptics, storage) belong to App.jsx.

import { DEFAULTS } from '../lib/seed.js';
import { computeStreak } from '../lib/helpers.js';

export const DEFAULT_SETTINGS = {
  autoDeleteCompletedDays: 7,
  weekStartsOn: 'monday',
  showOverdue: true,
  hapticFeedback: true,
  lastArchivedWeek: null, // YYYY-MM-DD of the week-start of the last archived week
  lastCleanupDate: null,  // YYYY-MM-DD when cleanup last ran
  lastRollDate: null,     // YYYY-MM-DD when recurring tasks last rolled forward
};

export const PERSISTED_KEYS = [
  'spaces', 'tasks', 'events', 'habits', 'settings',
  'archive', 'kits', 'plan', 'sessions',
];

export const initialState = {
  ...DEFAULTS,
  settings: DEFAULT_SETTINGS,
};

// --- Workout session math (shared by the reducer and App's haptics) ---

export const kitTotalSets = (kit) =>
  kit.exercises.reduce((a, e) => a + e.sets, 0);

export const kitDoneSets = (kit, ex) =>
  kit.exercises.reduce((a, e) => a + Math.min(ex?.[e.id]?.done || 0, e.sets), 0);

export const isSessionComplete = (kit, ex) => {
  const total = kitTotalSets(kit);
  return total > 0 && kitDoneSets(kit, ex) >= total;
};

// Toggle one completion date on a habit, recomputing streaks.
const toggleCompletion = (habit, dateISO) => {
  const has = habit.completions.includes(dateISO);
  const completions = has
    ? habit.completions.filter(d => d !== dateISO)
    : [...habit.completions, dateISO];
  const streakCurrent = computeStreak(completions, habit.frequency, habit.customDays);
  return {
    ...habit, completions, streakCurrent,
    streakBest: Math.max(habit.streakBest, streakCurrent),
  };
};

const upsertById = (list, item) =>
  list.some(x => x.id === item.id)
    ? list.map(x => x.id === item.id ? item : x)
    : [...list, item];

export function reducer(state, action) {
  switch (action.type) {
    case 'load':
      return action.state;

    case 'task/add':
      return { ...state, tasks: [...state.tasks, action.task] };
    case 'task/update':
      return { ...state, tasks: state.tasks.map(t => t.id === action.id ? { ...t, ...action.patch } : t) };
    case 'task/toggle':
      return { ...state, tasks: state.tasks.map(t => t.id === action.id ? { ...t, done: !t.done } : t) };
    case 'task/delete':
      return { ...state, tasks: state.tasks.filter(t => t.id !== action.id) };

    case 'event/add':
      return { ...state, events: [...state.events, action.event] };
    case 'event/update':
      return { ...state, events: state.events.map(e => e.id === action.id ? { ...e, ...action.patch } : e) };
    case 'event/delete':
      return { ...state, events: state.events.filter(e => e.id !== action.id) };

    case 'habit/add':
      return { ...state, habits: [...state.habits, action.habit] };
    case 'habit/update':
      return { ...state, habits: state.habits.map(h => h.id === action.id ? { ...h, ...action.patch } : h) };
    case 'habit/delete':
      return { ...state, habits: state.habits.filter(h => h.id !== action.id) };
    case 'habit/toggleDay':
      return { ...state, habits: state.habits.map(h => h.id === action.id ? toggleCompletion(h, action.date) : h) };

    case 'space/save':
      return { ...state, spaces: upsertById(state.spaces, action.space) };
    case 'space/delete':
      // Items keep their spaceId; rendering treats a missing space as "no label".
      return { ...state, spaces: state.spaces.filter(s => s.id !== action.id) };

    case 'settings/update':
      return { ...state, settings: { ...state.settings, ...action.partial } };

    case 'kit/save':
      return { ...state, kits: upsertById(state.kits, action.kit) };
    case 'kit/delete': {
      const plan = { ...state.plan };
      for (const k of Object.keys(plan)) if (plan[k] === action.id) plan[k] = null;
      return { ...state, kits: state.kits.filter(k => k.id !== action.id), plan };
    }

    case 'plan/update':
      return { ...state, plan: { ...state.plan, ...action.partial } };

    case 'session/upsert': {
      const { session } = action;
      const existing = state.sessions.find(s => s.date === session.date);
      const merged = existing ? { ...existing, ...session } : { id: action.id, ...session };
      const sessions = existing
        ? state.sessions.map(s => s.date === session.date ? merged : s)
        : [...state.sessions, merged];

      // Completing all sets auto-checks the linked habit for that day.
      let habits = state.habits;
      const kit = state.kits.find(k => k.id === merged.kitId);
      if (kit && kit.exercises.length && state.plan.linkedHabitId) {
        const nowComplete = isSessionComplete(kit, merged.ex);
        const wasComplete = existing ? isSessionComplete(kit, existing.ex) : false;
        if (nowComplete && !wasComplete) {
          habits = habits.map(h =>
            h.id === state.plan.linkedHabitId && !h.completions.includes(merged.date)
              ? toggleCompletion(h, merged.date)
              : h
          );
        }
      }
      return { ...state, sessions, habits };
    }

    case 'import':
      return { ...state, ...action.payload };

    case 'reset':
      return { ...initialState };

    default:
      return state;
  }
}

// Validate a parsed backup file and return only the slices Focl knows,
// with malformed entries dropped. Throws if nothing usable is found.
export function sanitizeImport(raw) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    throw new Error('Not a Focl backup file');
  }
  // v2 backups nest the slices under `data`; v1 had them at the top level.
  const src = raw.data && typeof raw.data === 'object' ? raw.data : raw;

  const out = {};
  for (const key of ['spaces', 'tasks', 'events', 'habits', 'kits', 'sessions']) {
    if (Array.isArray(src[key])) {
      out[key] = src[key].filter(x => x && typeof x === 'object' && x.id != null);
    }
  }
  if (src.plan && typeof src.plan === 'object' && !Array.isArray(src.plan)) {
    out.plan = src.plan;
  }

  if (Object.keys(out).length === 0) {
    throw new Error('No Focl data found in this file');
  }
  return out;
}
